clone:
  git:
    image: woodpeckerci/plugin-git

when:
  branch: main
  event: [push, cron]

steps:
  build:
    image: alpine:edge
    commands:
      - apk add --no-cache mdbook
      - mdbook build

  publish:
    image: bitnami/git
    environment:
      MDBOOK_OUTPUT: book
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/$CI_REPO.git $CI_REPO_NAME
      - cp -ar $MDBOOK_OUTPUT/. $CI_REPO_NAME/
      - cd $CI_REPO_NAME
      - git add .
      - git commit -m "Woodpecker CI ${CI_BUILD_CREATED}"
      - git push
